### ISSUE TITLE
External 'show' command

### ISSUE THREAD

**Issue by rripio** [rripio/pre.di.c#6]
Something that talks with the running server, instead of a standalone program that has great delays in loading and importing everything needed.

**Comment by rripio** [comment]
Maybe a server command to change temporarily stout and restore it after command's end.

**Comment by Rsantct** [comment]
Hi, could you please explain a bit more about this issue?

**Comment by Rsantct** [comment]
Oops, I did not know about de 'show' command :-)

predic.show() uses print() that writes the report to stdout.

I have modified predic.show() in order to write the report also to /tmp/predic. You can see it in my [fork](https://github.com/Rsantct/pre.di.c/blob/master/bin/predic.py).

Then you can use the following enclosed in a shorthand script for you to see the show report under your new terminal:

`echo show | nc -N localhost 9999 > /dev/null; cat /tmp/predic`

**Comment by rripio** [comment]
Yes, this last would be great, but somehow we have it with the standard server answer to any command.  In the meantime, I like your idea of writing to a tmp file.

I've implemented that with a new function in _~/bin/predic.py_ that is called with the _show_ command. That function just temporarily redirects stdout and call the previous _show()_ function as is.

This mod _~/bin/predic.py_ and _~/bin/server_process.py_
