### ISSUE TITLE
Review time.sleep() statements in start and stop scripts

### ISSUE THREAD

**Issue by rripio** [rripio/pre.di.c#8]
Too much of them. See how to re-implement wait4() for this cases.

**Comment by Rsantct** [comment]
Hi,

I have tried some tunning replacing `time.sleep` by `wait4result` inside `stopaudio.py`, it can be found [here](https://github.com/Rsantct/pre.di.c/blob/master/bin/stopaudio.py).

Current `time.sleep` inside `startaudio.init_inputs()` seemed not useful since core ports are ready but player_loops are not still.

Also, after tunning sleeps into `stopaudio.py` the `time.sleep` at  `startaudio.__main__()` seems to be not necessary.

I have tested it in a modest machine (Raspberry Pi3). Hope you can test it.

**Comment by rripio** [comment]
I'm reopening this because some problems has arousen while testing the above mods.

**Comment by rripio** [comment]
> Current time.sleep inside startaudio.init_inputs() seemed not useful since core ports are ready but player_loops are not still.

This seem not to be true. If restoring *mpd* input it will fail if we don't wait some time for the loop to be up.

**Comment by Rsantct** [comment]
Ok, it is necessary to check until the required input['in_ports'] are available.

A little more code inside `startaudio.init_inputs()` can fix this, you can find it [here](https://github.com/Rsantct/pre.di.c/blob/master/bin/startaudio.py). Hope it works ;-)

**Comment by rripio** [comment]
This seem elegant and practical. I'm going to try it with a little separated function to check for the ports existence, thank you!

**Comment by rripio** [comment]
Ok, finally I decided not to write a one shot function, and do what you wrote. Check, if you want, some changes in style. See also that time.sleep() should refer to configuration variable command_delay. That way one can fine tune waiting times of the whole thing just scaling one variable. Let's do that way all along pre.di.c :-)
Maybe there are still some hardwired times here and there, they will eventually get purged with code revisions.
It works nice and I'm closing this, thank you!
